In [6]:
import numpy as np

# Tạo ma trận ngẫu nhiên với giá trị từ -100 đến 100, kích thước N x M
N, M = 3, 3  # Có thể thay đổi giá trị này
a = np.random.randint(-100, 101, (N, M))

print("Matrix A:")
print(a)

# (1) Tính định thức của ma trận
if N == M:  # Chỉ tính định thức khi ma trận là vuông
    determinant = np.linalg.det(a)
    print("\nDeterminant of A:", determinant)
else:
    print("\nCannot calculate determinant because the matrix is not square.")

# (2) Tìm ma trận nghịch đảo
if N == M and np.linalg.det(a) != 0:  # Điều kiện để tồn tại ma trận nghịch đảo
    inverse_matrix = np.linalg.inv(a)
    print("\nInverse matrix of A:")
    print(inverse_matrix)
else:
    print("\nMatrix A is not invertible.")

Matrix A:
[[-53 -93 -33]
 [ 69  26  94]
 [ 59 -59 -84]]

Determinant of A: -1048026.9999999988

Inverse matrix of A:
[[-0.00320793  0.00559623  0.00752271]
 [-0.01082224 -0.00610576 -0.00258104]
 [ 0.00534814  0.00821925 -0.00480808]]


In [7]:
# (3) Sắp xếp ma trận theo hàng
a_sorted_rows = np.sort(a, axis=1)
print("\nMatrix sorted by row:")
print(a_sorted_rows)

# (4) Sắp xếp ma trận theo cột
a_sorted_columns = np.sort(a, axis=0)
print("\nMatrix sorted by column:")
print(a_sorted_columns)


Matrix sorted by row:
[[-93 -53 -33]
 [ 26  69  94]
 [-84 -59  59]]

Matrix sorted by column:
[[-53 -93 -84]
 [ 59 -59 -33]
 [ 69  26  94]]


In [8]:
# (5) Sắp xếp ma trận theo giá trị trung bình mỗi hàng
row_means = np.mean(a, axis=1)
sorted_indices = np.argsort(row_means)
a_sorted_by_mean = a[sorted_indices]
print("\nMatrix sorted by row mean:")
print(a_sorted_by_mean)

# (6) Thay đổi giá trị của một phần tử trong ma trận
row_index = int(input("\nEnter row index to change: "))
col_index = int(input("Enter column index to change: "))
new_value = int(input("Enter new value: "))
a[row_index, col_index] = new_value
print("\nUpdated Matrix A:")
print(a)


Matrix sorted by row mean:
[[-53 -93 -33]
 [ 59 -59 -84]
 [ 69  26  94]]

Updated Matrix A:
[[-53 -93  45]
 [ 69  26  94]
 [ 59 -59 -84]]


In [9]:
# (7) Thay đổi giá trị của một cột theo điều kiện
col_to_change = int(input("\nEnter column index to increment by 2: "))
a[:, col_to_change] += 2
print("\nMatrix after column update:")
print(a)

# (8) Thêm một vector vào từng hàng của ma trận
vector = np.random.randint(-10, 11, M)  # Tạo vector ngẫu nhiên có cùng số cột với ma trận
a_added_vector = a + vector
print("\nMatrix after adding vector to each row:")
print(a_added_vector)


Matrix after column update:
[[-53 -91  45]
 [ 69  28  94]
 [ 59 -57 -84]]

Matrix after adding vector to each row:
[[-48 -86  48]
 [ 74  33  97]
 [ 64 -52 -81]]


In [10]:
# (9) Tính hạng của ma trận
rank = np.linalg.matrix_rank(a)
print("\nRank of the matrix:", rank)

# (10) Phân rã giá trị kỳ dị (SVD)
U, S, V = np.linalg.svd(a)
print("\nMatrix U:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nMatrix V:")
print(V)



Rank of the matrix: 3

Matrix U:
[[ 0.0435045   0.90716602  0.41851783]
 [-0.73266774 -0.25582392  0.63067591]
 [ 0.67919463 -0.33407175  0.65352178]]

Singular values (S):
[139.72696598 119.60502363  86.33083632]

Matrix V:
[[-0.09151655 -0.45222266 -0.88719749]
 [-0.71436701 -0.59088728  0.37487597]
 [ 0.69376112 -0.66809197  0.26897698]]
